#!/usr/bin/env bash
# scripts/install-freeze-hook.sh
#
# Wires scripts/donna-freeze.sh into .git/hooks/commit-msg.
#
# Why a separate installer: git hooks aren't versioned (they live under
# .git/, which isn't tracked). The hook script itself IS versioned (in
# scripts/), and this installer wires the hook to call it. So updates
# to scripts/donna-freeze.sh take effect immediately without re-installing.
#
# Re-run this any time .git/hooks/commit-msg is missing (e.g., after a
# fresh clone) or after editing scripts/donna-freeze.sh structurally.
#
# Usage:
#   bash scripts/install-freeze-hook.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "$REPO_ROOT" ]]; then
    echo "Error: not inside a git repository." >&2
    exit 1
fi

SCRIPT_PATH="$REPO_ROOT/scripts/donna-freeze.sh"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_PATH="$HOOK_DIR/commit-msg"

if [[ ! -f "$SCRIPT_PATH" ]]; then
    echo "Error: cannot find $SCRIPT_PATH" >&2
    echo "       This installer must run from inside the donna repo." >&2
    exit 1
fi

mkdir -p "$HOOK_DIR"

# The shim. We don't copy donna-freeze.sh into .git/hooks/ — we install
# a tiny wrapper that always re-resolves and execs the versioned script.
# This way, edits to scripts/donna-freeze.sh take effect on the next
# commit without needing to re-install.
cat > "$HOOK_PATH" <<'EOF'
#!/usr/bin/env bash
# Installed by scripts/install-freeze-hook.sh
# DO NOT EDIT THIS FILE.
# Edit scripts/donna-freeze.sh instead, then re-run install-freeze-hook.sh
# (only needed if the shim itself changes; donna-freeze.sh edits take
# effect immediately).
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec bash "$REPO_ROOT/scripts/donna-freeze.sh" "$@"
EOF

chmod +x "$HOOK_PATH"

echo "Installed: $HOOK_PATH"
echo "  - Wired to: $SCRIPT_PATH"
echo "  - Edits to donna-freeze.sh take effect immediately."
echo
echo "Test the hook:"
echo "  bash scripts/test-freeze-hook.sh"
echo
echo "Bypass for an out-of-scope commit:"
echo "  git commit --no-verify"
