SLACK_BOT_TOKEN: ENC[AES256_GCM,data:kcVoT0odpGemBnlYe2oEoVp2egpDu5ujHc8HjQ+R3/0ncc41FfQrfp60819bwT9lc/dKIjQf5x1ryw==,iv:V6n0r7A9bC2AXID1A6XShKNs07wdHaivf1xsjbB7tGQ=,tag:s8VHhZ9GBD3KHlaQyPgMmg==,type:str]
SLACK_APP_TOKEN: ENC[AES256_GCM,data:w4pfovGg/g/q8EW9dxoQHB/ccxPaO9pzhkYZRQvQt+SWQkwHOzN79aqdJCbuBZcJNyssQq7MeGkNvTxXb4GEP8bttSj26LS/KTibCH+agCrKI1sV07YaiNlOsWfOTjPp36s=,iv:MxR65NmtR3bMHspMvaHmkaCqQ5/+Kea/LZ8YUduL4zM=,tag:yA8j8Y82bNYVsm3fObgRvg==,type:str]
SLACK_TEAM_ID: ENC[AES256_GCM,data:nsQOf90Vf40B6bk=,iv:XtAiGI2iso8Sew/EQWOdxwQkQ/GusAKjsGj6P2E43Yc=,tag:GNsv3w/zBGDmKkHtY4Todw==,type:str]
SLACK_ALLOWED_USER_ID: ENC[AES256_GCM,data:VAhQHSm5U64crBU=,iv:d0BJ2kHWChSRHJPl8AH4hzF50p13qdMJvf8+NtrsbiM=,tag:VeLzJdaeqyUw56KEQ/M+Ng==,type:str]
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:/SuKyBsTm7YPqAec9we+q7zfjxFhxtSireLC/JIK9tmgI92G9S8V9NbGPheyQCJvaf/eFXIEjLd51jN8uNexEjOkBb9EqldqSvtnqxqHN0C63ZvlsCkk+6NRQtqiOkMwz5kTg1DNlTONHKCK,iv:Uog484HmtxuMIb+1mtU8hl+rp31SabnuzZa705j8In8=,tag:4drBcjdFTObDZUrTd5UpEQ==,type:str]
TAVILY_API_KEY: ENC[AES256_GCM,data:033el+LcodSLaqMaDjbO91koQ1k3UftDUHxNH0e3fvXc70o2pd696zuXc6EWSjN0sL5ZdPtnzmnNCw==,iv:UeOIgA6iZVNQ9+XrhlQtBl9q86y0Wcof4+ei9U4VBWI=,tag:cCYd4aZDhPCioLQKwFXcBQ==,type:str]
VOYAGE_API_KEY: ENC[AES256_GCM,data:PFVPUOhEELFFwMKqLRqSYwW8RdznRG24r6xGDVUqJxEA8AYozqDaVCarYCWjeQ==,iv:2I+RldxNaXx72TIT3uE1mYzznzC50Aa5tDtlyP5PMGg=,tag:36DBMxvpOOTggqqHCRNxww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txwts2pk99ywrkhhj4clm2xgx74vm9nr3427j09txcnsxvn584zsgjy2ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZGJJVEIyL004YUhrd2hW
            TlZIM2JlT3B4bHJvbzdmWlVjUlRuVUJobW5BCkdhZlJncXFaSXZSRG9vOTNqcGp4
            eFIwU2lrK1NHOU1Zczd3VDJSOXNRYVEKLS0tIGo3NnVnbEYxRnNIbGdpZzkwekJm
            dEVIZUN3aDBkOFpFT3Y4WHZlRlFhbHcKGRC4xrkEVGMR1ELlUa/Cak1+1h7lJDjO
            xCnwsA9muPQNupSzhONEfFeN8gw3kZ/Hk4+VEhGB9FWWQFNAlOWkUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age155ljcfqv67mm9ras7j2pmgc03dffq3d4kt9r3j7qcfktm0uaefvqma5pmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU1hzUzdEWC8zM2RqYUZa
            NUFzcnJka043WFNaL0Jwc0ZkVzI1TUs2UGlzCjZSVG52ampxTGo2MEJxcVZETG16
            djYrRXpRSmt0TFJXWlgvQVNOb01xRXcKLS0tIGtLWjRpOTg4WEw2WnMxSHJqcUky
            UzJ0a2tmQlZEdDRzbWVJYUl5aENOTzgKusxSnn/6v++nWc+RNWKgweJFBDyffJ9/
            BshXFEsReGtAQvwfE286TyLEcjZLux5UtcQbxJB5Ku3Keyv1JvQxdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:03:42Z"
    mac: ENC[AES256_GCM,data:nMEAidrujj6EhjDah3GwBanUCtvHovh0dmcpUovG+AuZ5TwwcBl9IZFqg4K5DWmlX4s3tg5qA0Ok8rh9PuvXHR9CdpFuIH9gQeOcYFDa6AyL/W+mVVBJqsUScD3j3ahaT0txgjuoa/DBoBuaM6QWhRs+fIPS6oM1Uj8ZnDWPLos=,iv:BwqLi1rWAo8yCR+5DXjM9vD+bUGVQcNitbKOzOCC+sY=,tag:fhh7245GJT7v2i9iMQF1pQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.12.2
