DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:VAFxzt4wlh9T424oPQ/beQZmB5IM1pB8936ANGLlB6HcnFX++in6F3s0dsre2ZnPJvR3S6EbvvB+x064lxyLIRzJToI1YAwL,iv:BgSw5TJjpsWMowTteMW88dEZGbZbOVJQnHJeYGvd1y0=,tag:esf6vrgcmBbJMDqE/epbPg==,type:str]
DISCORD_ALLOWED_USER_ID: ENC[AES256_GCM,data:WGIUY0aSajVitdKE/PpqudM6+w==,iv:5ohUMR6FkiHkBqlM8tPugcy4p7ohIwgXpzLDGzajCcU=,tag:DbweXp2hILMG44ZIs5ENfQ==,type:str]
DISCORD_GUILD_ID: ENC[AES256_GCM,data:en8+CES0vCiP6CXXmFRG7njQ6w==,iv:BJKpNNxyfoA5VYfkeG98gXc/qBCdCD26CJqtiEPgXpY=,tag:24UGHX+3/Rg6SSbGQgHLhg==,type:str]
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:/SuKyBsTm7YPqAec9we+q7zfjxFhxtSireLC/JIK9tmgI92G9S8V9NbGPheyQCJvaf/eFXIEjLd51jN8uNexEjOkBb9EqldqSvtnqxqHN0C63ZvlsCkk+6NRQtqiOkMwz5kTg1DNlTONHKCK,iv:Uog484HmtxuMIb+1mtU8hl+rp31SabnuzZa705j8In8=,tag:4drBcjdFTObDZUrTd5UpEQ==,type:str]
TAVILY_API_KEY: ENC[AES256_GCM,data:033el+LcodSLaqMaDjbO91koQ1k3UftDUHxNH0e3fvXc70o2pd696zuXc6EWSjN0sL5ZdPtnzmnNCw==,iv:UeOIgA6iZVNQ9+XrhlQtBl9q86y0Wcof4+ei9U4VBWI=,tag:cCYd4aZDhPCioLQKwFXcBQ==,type:str]
VOYAGE_API_KEY: ENC[AES256_GCM,data:PFVPUOhEELFFwMKqLRqSYwW8RdznRG24r6xGDVUqJxEA8AYozqDaVCarYCWjeQ==,iv:2I+RldxNaXx72TIT3uE1mYzznzC50Aa5tDtlyP5PMGg=,tag:36DBMxvpOOTggqqHCRNxww==,type:str]
sops:
    age:
        - recipient: age1txwts2pk99ywrkhhj4clm2xgx74vm9nr3427j09txcnsxvn584zsgjy2ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZGJJVEIyL004YUhrd2hW
            TlZIM2JlT3B4bHJvbzdmWlVjUlRuVUJobW5BCkdhZlJncXFaSXZSRG9vOTNqcGp4
            eFIwU2lrK1NHOU1Zczd3VDJSOXNRYVEKLS0tIGo3NnVnbEYxRnNIbGdpZzkwekJm
            dEVIZUN3aDBkOFpFT3Y4WHZlRlFhbHcKGRC4xrkEVGMR1ELlUa/Cak1+1h7lJDjO
            xCnwsA9muPQNupSzhONEfFeN8gw3kZ/Hk4+VEhGB9FWWQFNAlOWkUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age155ljcfqv67mm9ras7j2pmgc03dffq3d4kt9r3j7qcfktm0uaefvqma5pmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU1hzUzdEWC8zM2RqYUZa
            NUFzcnJka043WFNaL0Jwc0ZkVzI1TUs2UGlzCjZSVG52ampxTGo2MEJxcVZETG16
            djYrRXpRSmt0TFJXWlgvQVNOb01xRXcKLS0tIGtLWjRpOTg4WEw2WnMxSHJqcUky
            UzJ0a2tmQlZEdDRzbWVJYUl5aENOTzgKusxSnn/6v++nWc+RNWKgweJFBDyffJ9/
            BshXFEsReGtAQvwfE286TyLEcjZLux5UtcQbxJB5Ku3Keyv1JvQxdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T14:18:43Z"
    mac: ENC[AES256_GCM,data:26yPoN2Y5CwCxIvFEjBX/tbjQLBMdqb3xgBSIMBoKNjiKW+Z4K3XNNA4wbD7Y4cwJLREE0/vuDAuoN5hFzSGbPZBVVPCIODkliGJsvPQm2Ai/+2eUiAA5G6/ObxAaF4Mg/ZoR3yPntbgsCdegh4X/7ic39mB4lYQEkXf1sW4FcA=,iv:068Eg7Sarpygtr5EVuf5noJtnEHruXVs3PRFUQdlP6I=,tag:VIGArFbyTLWx+bseeJVIDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
